# Generated by Django 3.2.5 on 2021-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='identity_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
