# Generated by Django 3.2.5 on 2021-08-01 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_price_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='purchase.price'),
        ),
    ]
