# Generated by Django 3.2.5 on 2021-08-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='verify',
        ),
    ]
