# Generated by Django 3.2.5 on 2021-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_payment_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='duration',
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
