# Generated by Django 3.2.5 on 2021-08-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20210801_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchase.product')),
                ('duration', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('purchase.product',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='duration',
        ),
    ]
