# Generated by Django 3.2.6 on 2021-08-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20210804_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type_id',
            field=models.IntegerField(choices=[(1, 'Remission'), (2, 'Cash'), (3, 'Online'), (4, 'Free')], null=True),
        ),
    ]
