# Generated by Django 3.2.6 on 2021-08-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_payment_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_limit',
            field=models.IntegerField(null=True),
        ),
    ]
